spring:
  datasource:
    url: jdbc:mysql://localhost:3306/project_userManagementMicroService
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Daten4you2024
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
#  jpa:
#    properties:
#      hibernate:
#        auto_quote_keyword: true
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: only.for.it.2023@gmail.com
#    password: tvnjloqqlbeatyhk
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#          ssl:
#            protocols: TLSv1.2
#            trust: smtp.gmail.com
#        debug: true


key:
  access: Dm7QXW4YowIjJcIV/Qbs4u9R/RCCTPqeg7mkhaCJ6tA=
  refresh: 3zT4pEV8P/GQ6hTpjaZTsY8KRft4l6l0qtaCgWk5djg=

logging:
  file:
    name: logs/log.log
  level:
    root: debug


